In [33]:
from docplex.mp.model import Model
import numpy as np

# Sample data
X = np.random.randint(100, size=(4, 10))

y = np.random.randint(100, size=(4, 1)).reshape(-1)

n, p = X.shape

# Create the model
mdl = Model("LinearRegression")

# Define the variables for regression coefficients
beta = mdl.continuous_var_list(p, name="beta")

# Define the quadratic objective
XT_X = np.dot(X.T, X)
XT_y = np.dot(X.T, y)
obj = 0.5 * mdl.sum(XT_X[i][j] * beta[i] * beta[j] for i in range(p) for j in range(p)) - mdl.sum(XT_y[i] * beta[i] for i in range(p)) + 0.5 * np.dot(y, y)

mdl.minimize(obj)

# Solve the model
mdl.solve()

b = [v.solution_value for v in beta]
# Print the solution
for v in beta:
    print(f"{v.name} = {v.solution_value}")




beta_0 = 2.3306196453868318e-08
beta_1 = 4.4477683303601064e-08
beta_2 = 0.6670070153309257
beta_3 = 1.4959215580282613e-08
beta_4 = 0.3182671405910768
beta_5 = 1.6734899953778344e-08
beta_6 = 1.1470420077846508e-08
beta_7 = 8.204124031817441e-09
beta_8 = 0.36929348868930784
beta_9 = 1.2008052797460477e-08


In [39]:
print(X)
print(y)
np.sum(X * b, axis=1)


[[48 51 41 69 14 53 59 96  7 52]
 [59  4 67  5 95 93 46 98 54 39]
 [51 15 12 29 18 16 62 18 91 57]
 [54 89 89 61 22  8 11  0 57  0]]
[33 95 47 88]


array([34.38808941, 94.86670176, 47.33860429, 87.4152367 ])